import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1701374308304 implements MigrationInterface {
    name = 'AutoGeneratedMigrations1701374308304'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "description"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "category" ADD "description" character varying NOT NULL`);
    }

}
