version: '3'
services:
  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
    command: npm run start
